#!/usr/bin/env python3
"""
Render bugs/log.jsonl into a human-readable BUGS.md at the repo root.

The render groups by status: open + deferred surface first (the live
backlog), then fixed (the engineering-discipline trail), then
wontfix/cant_reproduce. Within each group, sort by severity then by id.

Usage:  python bugs/render.py
"""
from __future__ import annotations

from collections import Counter
from pathlib import Path

from _lib import load

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "BUGS.md"

SEVERITY_RANK = {"blocker": 0, "major": 1, "minor": 2, "cosmetic": 3}
STATUS_ORDER = ["open", "deferred", "fixed", "wontfix", "cant_reproduce"]
STATUS_HEADING = {
    "open": "Open",
    "deferred": "Deferred",
    "fixed": "Fixed",
    "wontfix": "Won't fix",
    "cant_reproduce": "Can't reproduce",
}


def _badge(text: str) -> str:
    """Inline pseudo-badge using markdown's backtick code style."""
    return f"`{text}`"


def render_entry(e: dict) -> list[str]:
    out = []
    title = e["title"]
    out.append(f"### {e['id']} — {title}")
    out.append("")
    meta = [
        _badge(f"severity:{e['severity']}"),
        _badge(f"status:{e['status']}"),
        _badge(f"discovered:{e['discovered_at']}"),
    ]
    if e.get("discovered_in_commit"):
        meta.append(_badge(f"introduced-in:{e['discovered_in_commit']}"))
    if e.get("fix") and e["fix"].get("commit"):
        meta.append(_badge(f"fixed-in:{e['fix']['commit']}"))
    for t in e.get("tags", []):
        meta.append(_badge(f"#{t}"))
    out.append(" ".join(meta))
    out.append("")

    out.append(f"**Discovered during:** {e['discovered_during']}")
    out.append("")
    out.append("**Symptom**")
    out.append("")
    out.append(e["symptom"])
    out.append("")
    out.append("**Reproduction**")
    out.append("")
    out.append(e["repro"])
    out.append("")
    if e.get("root_cause"):
        out.append("**Root cause**")
        out.append("")
        out.append(e["root_cause"])
        out.append("")
    if e.get("fix"):
        out.append("**Fix**")
        out.append("")
        out.append(f"`{e['fix']['commit']}` — {e['fix']['summary']}")
        out.append("")
    if e.get("notes"):
        out.append("**Notes**")
        out.append("")
        out.append(e["notes"])
        out.append("")
    out.append("---")
    out.append("")
    return out


def main():
    entries = load()
    if not entries:
        OUT.write_text("# Bug log\n\n(no bugs logged yet)\n")
        print(f"Wrote {OUT.relative_to(REPO_ROOT)} (empty)")
        return

    by_status: dict[str, list[dict]] = {s: [] for s in STATUS_ORDER}
    for e in entries:
        by_status.setdefault(e["status"], []).append(e)
    for s in by_status:
        by_status[s].sort(key=lambda e: (SEVERITY_RANK.get(e["severity"], 99), e["id"]))

    counts = Counter(e["status"] for e in entries)
    sev_counts = Counter(e["severity"] for e in entries if e["status"] == "open")

    lines: list[str] = []
    lines.append("# Bug log")
    lines.append("")
    lines.append(
        "Source of truth: [`bugs/log.jsonl`](bugs/log.jsonl). This file is "
        "generated by `python bugs/render.py` — don't edit it by hand."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    summary_bits = [f"{counts.get(s, 0)} {STATUS_HEADING[s].lower()}" for s in STATUS_ORDER if counts.get(s)]
    lines.append("- " + " · ".join(summary_bits))
    if sev_counts:
        sev_bits = [f"{sev_counts[k]} {k}" for k in ["blocker", "major", "minor", "cosmetic"] if sev_counts.get(k)]
        lines.append(f"- Open by severity: {', '.join(sev_bits)}")
    lines.append("")

    for status in STATUS_ORDER:
        bucket = by_status.get(status, [])
        if not bucket:
            continue
        lines.append(f"## {STATUS_HEADING[status]}")
        lines.append("")
        for e in bucket:
            lines.extend(render_entry(e))

    OUT.write_text("\n".join(lines))
    print(
        f"Wrote {OUT.relative_to(REPO_ROOT)}: "
        f"{sum(counts.values())} bugs ({counts.get('open', 0)} open)"
    )


if __name__ == "__main__":
    main()
